// GENERATED by `supabase gen types typescript` — do not edit by hand.
// Regenerate with `npm run gen:types` after any schema migration.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.15"
  }
  public: {
    Tables: {
      app_content: {
        Row: {
          key: string
          value: Json
        }
        Insert: {
          key: string
          value: Json
        }
        Update: {
          key?: string
          value?: Json
        }
        Relationships: []
      }
      basket_items: {
        Row: {
          added_at: string
          id: string
          recipe_slug: string
          user_id: string
        }
        Insert: {
          added_at?: string
          id: string
          recipe_slug: string
          user_id: string
        }
        Update: {
          added_at?: string
          id?: string
          recipe_slug?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "basket_items_recipe_slug_fkey"
            columns: ["recipe_slug"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["slug"]
          },
        ]
      }
      cuisines: {
        Row: {
          code: string
          label: string
          sort_order: number
        }
        Insert: {
          code: string
          label: string
          sort_order: number
        }
        Update: {
          code?: string
          label?: string
          sort_order?: number
        }
        Relationships: []
      }
      exercises: {
        Row: {
          category: string
          cues: string[]
          kit_note: string | null
          name: string
          ramp_note: string | null
          rationale: string | null
          rest_seconds: number
          slug: string
          sort_order: number
          space_note: string | null
          swap_note: string | null
          video_url: string
        }
        Insert: {
          category: string
          cues?: string[]
          kit_note?: string | null
          name: string
          ramp_note?: string | null
          rationale?: string | null
          rest_seconds?: number
          slug: string
          sort_order: number
          space_note?: string | null
          swap_note?: string | null
          video_url: string
        }
        Update: {
          category?: string
          cues?: string[]
          kit_note?: string | null
          name?: string
          ramp_note?: string | null
          rationale?: string | null
          rest_seconds?: number
          slug?: string
          sort_order?: number
          space_note?: string | null
          swap_note?: string | null
          video_url?: string
        }
        Relationships: []
      }
      ingredient_categories: {
        Row: {
          code: string
          label: string
          sort_order: number
        }
        Insert: {
          code: string
          label: string
          sort_order: number
        }
        Update: {
          code?: string
          label?: string
          sort_order?: number
        }
        Relationships: []
      }
      meal_plan_entries: {
        Row: {
          id: string
          plan_date: string
          recipe_slug: string
          updated_at: string
          user_id: string
        }
        Insert: {
          id: string
          plan_date: string
          recipe_slug: string
          updated_at?: string
          user_id: string
        }
        Update: {
          id?: string
          plan_date?: string
          recipe_slug?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "meal_plan_entries_recipe_slug_fkey"
            columns: ["recipe_slug"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["slug"]
          },
        ]
      }
      operation_receipts: {
        Row: {
          created_at: string
          op: string
          operation_id: string
          result: Json
          user_id: string
        }
        Insert: {
          created_at?: string
          op: string
          operation_id: string
          result?: Json
          user_id: string
        }
        Update: {
          created_at?: string
          op?: string
          operation_id?: string
          result?: Json
          user_id?: string
        }
        Relationships: []
      }
      phases: {
        Row: {
          goal: string
          name: string
          notes: string | null
          short_label: string
          slug: string
          sort_order: number
          window_label: string
        }
        Insert: {
          goal: string
          name: string
          notes?: string | null
          short_label: string
          slug: string
          sort_order: number
          window_label: string
        }
        Update: {
          goal?: string
          name?: string
          notes?: string | null
          short_label?: string
          slug?: string
          sort_order?: number
          window_label?: string
        }
        Relationships: []
      }
      races: {
        Row: {
          created_at: string
          distance: number | null
          id: string
          is_target: boolean
          location: string | null
          name: string
          notes: string | null
          race_date: string
          unit: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          distance?: number | null
          id: string
          is_target?: boolean
          location?: string | null
          name: string
          notes?: string | null
          race_date: string
          unit?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          distance?: number | null
          id?: string
          is_target?: boolean
          location?: string | null
          name?: string
          notes?: string | null
          race_date?: string
          unit?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      recipe_ingredients: {
        Row: {
          category_code: string
          id: number
          ingredient_name: string
          quantity_text: string
          quantity_unit: string | null
          quantity_value: number | null
          recipe_slug: string
          sort_order: number
        }
        Insert: {
          category_code: string
          id?: number
          ingredient_name: string
          quantity_text: string
          quantity_unit?: string | null
          quantity_value?: number | null
          recipe_slug: string
          sort_order: number
        }
        Update: {
          category_code?: string
          id?: number
          ingredient_name?: string
          quantity_text?: string
          quantity_unit?: string | null
          quantity_value?: number | null
          recipe_slug?: string
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "recipe_ingredients_category_code_fkey"
            columns: ["category_code"]
            isOneToOne: false
            referencedRelation: "ingredient_categories"
            referencedColumns: ["code"]
          },
          {
            foreignKeyName: "recipe_ingredients_recipe_slug_fkey"
            columns: ["recipe_slug"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["slug"]
          },
        ]
      }
      recipe_steps: {
        Row: {
          id: number
          instruction: string
          recipe_slug: string
          step_no: number
        }
        Insert: {
          id?: number
          instruction: string
          recipe_slug: string
          step_no: number
        }
        Update: {
          id?: number
          instruction?: string
          recipe_slug?: string
          step_no?: number
        }
        Relationships: [
          {
            foreignKeyName: "recipe_steps_recipe_slug_fkey"
            columns: ["recipe_slug"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["slug"]
          },
        ]
      }
      recipes: {
        Row: {
          cost_band: string
          cuisine_code: string
          description: string | null
          diet_tag: string
          heat_level: number
          meal_type: string
          name: string
          serves: number
          slug: string
          sort_order: number
          spice_note: string | null
          time_minutes: number
          tip: string | null
        }
        Insert: {
          cost_band: string
          cuisine_code: string
          description?: string | null
          diet_tag: string
          heat_level: number
          meal_type: string
          name: string
          serves: number
          slug: string
          sort_order: number
          spice_note?: string | null
          time_minutes: number
          tip?: string | null
        }
        Update: {
          cost_band?: string
          cuisine_code?: string
          description?: string | null
          diet_tag?: string
          heat_level?: number
          meal_type?: string
          name?: string
          serves?: number
          slug?: string
          sort_order?: number
          spice_note?: string | null
          time_minutes?: number
          tip?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "recipes_cuisine_code_fkey"
            columns: ["cuisine_code"]
            isOneToOne: false
            referencedRelation: "cuisines"
            referencedColumns: ["code"]
          },
        ]
      }
      sauna_logs: {
        Row: {
          created_at: string
          duration_min: number | null
          id: string
          logged_on: string
          sauna_type_slug: string
          temp_c: number | null
          user_id: string
          weight_after_kg: number | null
          weight_before_kg: number | null
        }
        Insert: {
          created_at?: string
          duration_min?: number | null
          id: string
          logged_on: string
          sauna_type_slug: string
          temp_c?: number | null
          user_id: string
          weight_after_kg?: number | null
          weight_before_kg?: number | null
        }
        Update: {
          created_at?: string
          duration_min?: number | null
          id?: string
          logged_on?: string
          sauna_type_slug?: string
          temp_c?: number | null
          user_id?: string
          weight_after_kg?: number | null
          weight_before_kg?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "sauna_logs_sauna_type_slug_fkey"
            columns: ["sauna_type_slug"]
            isOneToOne: false
            referencedRelation: "sauna_types"
            referencedColumns: ["slug"]
          },
        ]
      }
      sauna_schedule: {
        Row: {
          day_of_week: number
          id: number
          is_optional: boolean
          note: string | null
          phase_slug: string
          sauna_type_slug: string
          slot_key: string
          sort_order: number
        }
        Insert: {
          day_of_week: number
          id?: number
          is_optional?: boolean
          note?: string | null
          phase_slug: string
          sauna_type_slug: string
          slot_key: string
          sort_order: number
        }
        Update: {
          day_of_week?: number
          id?: number
          is_optional?: boolean
          note?: string | null
          phase_slug?: string
          sauna_type_slug?: string
          slot_key?: string
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "sauna_schedule_phase_slug_fkey"
            columns: ["phase_slug"]
            isOneToOne: false
            referencedRelation: "phases"
            referencedColumns: ["slug"]
          },
          {
            foreignKeyName: "sauna_schedule_sauna_type_slug_fkey"
            columns: ["sauna_type_slug"]
            isOneToOne: false
            referencedRelation: "sauna_types"
            referencedColumns: ["slug"]
          },
        ]
      }
      sauna_types: {
        Row: {
          duration_label: string
          how_to: string[]
          name: string
          rationale: string
          slug: string
          sort_order: number
          temp_label: string
        }
        Insert: {
          duration_label: string
          how_to?: string[]
          name: string
          rationale: string
          slug: string
          sort_order: number
          temp_label: string
        }
        Update: {
          duration_label?: string
          how_to?: string[]
          name?: string
          rationale?: string
          slug?: string
          sort_order?: number
          temp_label?: string
        }
        Relationships: []
      }
      session_template_items: {
        Row: {
          exercise_slug: string
          id: number
          prescription: string
          session_template_slug: string
          sort_order: number
        }
        Insert: {
          exercise_slug: string
          id?: number
          prescription: string
          session_template_slug: string
          sort_order: number
        }
        Update: {
          exercise_slug?: string
          id?: number
          prescription?: string
          session_template_slug?: string
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "session_template_items_exercise_slug_fkey"
            columns: ["exercise_slug"]
            isOneToOne: false
            referencedRelation: "exercises"
            referencedColumns: ["slug"]
          },
          {
            foreignKeyName: "session_template_items_session_template_slug_fkey"
            columns: ["session_template_slug"]
            isOneToOne: false
            referencedRelation: "session_templates"
            referencedColumns: ["slug"]
          },
        ]
      }
      session_templates: {
        Row: {
          brief: string | null
          day_of_week: number
          duration_label: string
          name: string
          phase_slug: string
          session_key: string
          slug: string
          sort_order: number
        }
        Insert: {
          brief?: string | null
          day_of_week: number
          duration_label: string
          name: string
          phase_slug: string
          session_key: string
          slug: string
          sort_order: number
        }
        Update: {
          brief?: string | null
          day_of_week?: number
          duration_label?: string
          name?: string
          phase_slug?: string
          session_key?: string
          slug?: string
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "session_templates_phase_slug_fkey"
            columns: ["phase_slug"]
            isOneToOne: false
            referencedRelation: "phases"
            referencedColumns: ["slug"]
          },
        ]
      }
      shopping_checks: {
        Row: {
          checked_at: string
          id: string
          item_key: string
          user_id: string
        }
        Insert: {
          checked_at?: string
          id: string
          item_key: string
          user_id: string
        }
        Update: {
          checked_at?: string
          id?: string
          item_key?: string
          user_id?: string
        }
        Relationships: []
      }
      staples: {
        Row: {
          category_code: string
          id: number
          ingredient_name: string
          quantity_text: string
          quantity_unit: string | null
          quantity_value: number | null
          sort_order: number
        }
        Insert: {
          category_code: string
          id?: number
          ingredient_name: string
          quantity_text: string
          quantity_unit?: string | null
          quantity_value?: number | null
          sort_order: number
        }
        Update: {
          category_code?: string
          id?: number
          ingredient_name?: string
          quantity_text?: string
          quantity_unit?: string | null
          quantity_value?: number | null
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "staples_category_code_fkey"
            columns: ["category_code"]
            isOneToOne: false
            referencedRelation: "ingredient_categories"
            referencedColumns: ["code"]
          },
        ]
      }
      user_settings: {
        Row: {
          phase_override: string | null
          phase_override_from: string | null
          plan_start: string
          rest_overrides: Json
          theme: string
          updated_at: string
          user_id: string
        }
        Insert: {
          phase_override?: string | null
          phase_override_from?: string | null
          plan_start?: string
          rest_overrides?: Json
          theme?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          phase_override?: string | null
          phase_override_from?: string | null
          plan_start?: string
          rest_overrides?: Json
          theme?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_settings_phase_override_fkey"
            columns: ["phase_override"]
            isOneToOne: false
            referencedRelation: "phases"
            referencedColumns: ["slug"]
          },
        ]
      }
      workout_log_sets: {
        Row: {
          exercise_slug: string
          id: string
          reps: number
          set_no: number
          weight_kg: number
          workout_log_id: string
        }
        Insert: {
          exercise_slug: string
          id: string
          reps?: number
          set_no: number
          weight_kg?: number
          workout_log_id: string
        }
        Update: {
          exercise_slug?: string
          id?: string
          reps?: number
          set_no?: number
          weight_kg?: number
          workout_log_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "workout_log_sets_exercise_slug_fkey"
            columns: ["exercise_slug"]
            isOneToOne: false
            referencedRelation: "exercises"
            referencedColumns: ["slug"]
          },
          {
            foreignKeyName: "workout_log_sets_workout_log_id_fkey"
            columns: ["workout_log_id"]
            isOneToOne: false
            referencedRelation: "workout_logs"
            referencedColumns: ["id"]
          },
        ]
      }
      workout_logs: {
        Row: {
          created_at: string
          id: string
          logged_on: string
          notes: string | null
          phase_slug: string
          session_key: string
          session_name: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id: string
          logged_on: string
          notes?: string | null
          phase_slug: string
          session_key: string
          session_name: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          logged_on?: string
          notes?: string | null
          phase_slug?: string
          session_key?: string
          session_name?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      add_race: {
        Args: { p_as_target?: boolean; p_operation_id: string; p_race: Json }
        Returns: Json
      }
      prune_operation_receipts: { Args: never; Returns: number }
      require_uid: { Args: never; Returns: string }
      save_workout: {
        Args: { p_log: Json; p_operation_id: string; p_sets?: Json }
        Returns: Json
      }
      set_rest_override: {
        Args: {
          p_exercise_slug: string
          p_operation_id: string
          p_seconds: number
        }
        Returns: Json
      }
      set_target_race: {
        Args: { p_operation_id: string; p_race_id: string }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
